from solutions.y2024 import day_08


RAW_EXAMPLE = """\
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""


def test_day08_parts() -> None:
    grid, groups = day_08.parse(RAW_EXAMPLE)
    assert day_08.solve_part1(grid, groups) == 14
    assert day_08.solve_part2(grid, groups) == 34
