from solutions.y2024 import day_06


RAW_EXAMPLE = """\
....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
"""


def test_day06_parts() -> None:
    guard_map = day_06.parse(RAW_EXAMPLE)
    assert day_06.solve_part1(guard_map) == 41
    assert day_06.solve_part2(guard_map) == 6
